name: form_talk
description: Building forms in Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  quiver: ^2.1.0
  intl: ^0.16.1
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
